name: "build"

on:
    pull_request:
        branches:
            - master
            - v0.2
    push:
        branches:
            - master
            - v0.2

jobs:
    build:
        runs-on: ubuntu-20.04
        strategy:
            matrix:
                node: ["12", "14", "16"]
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node }}
            - run: npm install
            - run: npm run build
            - run: npm test
